version: '3'
services:
  node:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    container_name: ebla-api
    environment:
      TZ: "Asia/Tokyo"
      DB_PING_HOST: "ebla-db"
      DB_PING_USER: "ebla"
      DB_PING_PASS: "ebla"
    env_file:
      - .env
    ports:
      - 23000:3000

  proxy:
    image: nginx:stable
    container_name: ebla-proxy
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/localhost.ebla.r253hmdryou.dev.cert:/etc/nginx/localhost.ebla.r253hmdryou.dev.cert
    ports:
      - 80:80
      - 443:443


  mariadb:
    image: mariadb:10.6.8
    container_name: ebla-db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "ebla"
      MYSQL_DATABASE: "ebla"
      MYSQL_USER: "ebla"
      MYSQL_PASSWORD: "ebla"
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql

  jestdb:
    image: mariadb:10.6.8
    container_name: jest-db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "ebla"
      MYSQL_USER: "ebla"
      MYSQL_PASSWORD: "ebla"
    env_file:
      - .env.test
    ports:
      - 13306:3306
