openapi: "3.0.2"

info:
  version: "1.0.0"
  title: "ebla-api"
  description: "API for the Express Best Login API project"

servers:
- url: "http://localhost:3000"
  description: "Local server"

security:
- bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: "Bad request"
    UnauthorizedError:
      description: "Access token is missing or invalid"
    ForbiddenError:
      description: "Access token is valid but user does not have permission to access the resource"
    NotFound:
      description: "Entity not found"
    Conflict:
      description: "Entity already exists"
    InternalServerError:
      description: "Internal server error"

paths:
  /hello:
    get:
      summary: "Get Hello World"
      description: "Get Hello World"
      operationId: "getHelloWorld"
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: string
                example: "Hello World!"
